###전체 장소목록 확인하기
GET http://localhost:3000/locations


###이름으로 장소검색하기
GET http://localhost:3000/locationsByName?name=Location 1


###특정 사용자의 찜목록 조회하기
GET http://localhost:3000/scraps/user1@example.com


###특정 사용자가 찜 추가하기
POST http://localhost:3000/scraps/user1@example.com
Content-Type: application/json

{
    "locationId": "445bda27-260c-4afd-bb87-adea403773cd"
}

###특정 사용자가 찜 삭제하기
DELETE http://localhost:3000/scraps/user1@example.com
Content-Type: application/json

{
    "locationId": "445bda27-260c-4afd-bb87-adea403773cd"
}

###특정 사용자의 일정조회하기
GET http://localhost:3000/events/user1@example.com


###특정 장소를 사용자의 일정에 추가하기
POST http://localhost:3000/events
Content-Type: application/json

{
    "eventCreatorId": "user1@example.com",
    "eventDate": "2024-08-16T10:00:00Z",
    "locationId": "445bda27-260c-4afd-bb87-adea403773cd"
}


###특정 장소 사용자의 일정에서 삭제하기
DELETE http://localhost:3000/events/d95a47d9-9692-419b-99a5-b972c0ee5e19/location/0188fc65-283b-4ca1-bb8d-d2824a171c45


###특정 사용자의 특정 일정을 삭제하기
DELETE http://localhost:3000/events/date/2024-08-15


###카카오 로그인
GET http://localhost:3000/auth/kakao


### 특정 사용자가 장소 검색함
GET http://localhost:3000/locationsByName/445bda27-260c-4afd-bb87-adea403773cd